name: Python application

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    steps:
    - uses: actions/checkout@v2
    - name: 设置 Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: 运行测试
      run: |
        python run_test.py
